### ISSUE TITLE
To sign in 

### ISSUE THREAD

**Issue by Landry333** [Landry333/Big-Owl#145] opened 2020-11-07 19:57 UTC
Expected steps:

Preconditions: The tester installed the Big Owl application on a smartphone and has already created an account

1- Open the application
2- Make sure the app is connected to internet
3- If app is at registration page click on the "sign in at the bottom of page"
4- Enter email, password and click on "sign in " button

Expected result: The tester will be signed in, and see a profile with last name, full name, first name, phone number, and email on the homepage.

**Comment by refatK** [comment] 2020-11-10 21:51
Closed because duplicate of #146

**Closed** 2020-11-10 21:51 UTC
Labels: acceptance-test
